spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfd_prod
    username: sfd_prod_user
    password: drampas
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: false