spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfd_dev
    username: sfd_dev_user
    password: drampas
    platform: mysql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true
#    properties:
#     javax:
#        persistence:
#         schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: drampas_database_create.sql